### ISSUE TITLE
Preferred RPS

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-sdk-benchmark#30]
What's the guideline regarding RPS?

Python has 10:
https://github.com/getsentry/sentry-sdk-benchmark/blob/b115beb7854c199e85141e921df5642971e88106/platform/python/django/config.json#L5

Go has 100:
https://github.com/getsentry/sentry-sdk-benchmark/blob/b115beb7854c199e85141e921df5642971e88106/platform/go/go-std/config.json#L5

When finding the 'right' value for a new platform, what should we be considering?

**Comment by rhcarvalho** [comment]
That's something we don't have a guideline for yet.

Configuration may even depend on hardware, so eventually RPS and perhaps a few other knobs could become command line arguments.

Generally we're looking to throw enough load to see a "ramping up" curve of latency percentiles, while still running without errors (including timeout errors - 30s max wait time for each response).

The difference between Python/Node vs Go is just what it is... I'd expect .NET and Java to be have better performance than dynamic languages, so the starting RPS might be closer to 100 than to 10.

Would be interested to hear if 10/100 for the existing platforms make sense in your hardware.
